name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout

        uses: actions/checkout@v2

      - name: Deployment

        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}

          key: ${{ secrets.KEY }}

          username: ${{ secrets.USERNAME }}

          script: |
            cd /var/www/mytrans.uz/data/www/mytrans.uz/track
            git pull
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            php artisan migrate --force
            php artisan optimize
